[build]
  command = ""   # no build step
  publish = "."

# Redirect all www → apex
[[redirects]]
  from = "https://www.durangotango.info/*"
  to = "https://durangotango.info/:splat"
  status = 301
  force = true

